import assert from 'node:assert/strict';
import {
  fixture,
  api,
  start,
  stop,
  waitTask,
  create,
  calls,
} from './fixtures/flow-helper.mjs';
const f = fixture('docker-scheduler', {
    FIXTURE_DOCKER_GB: '16',
    FIXTURE_STOP_PROJECT: '1',
  }),
  original = (await api('/api/scheduler', null, 'GET')).config;
let child;
try {
  await api('/api/scheduler', {
    ...original,
    enabled: true,
    useHistory: false,
    repos: [f.bin],
    autoContinue: true,
    concurrency: 3,
    dailyLimit: 1,
  });
  const tasks = [];
  for (let i = 0; i < 3; i++)
    tasks.push(await create(f, '__DOCKER_PARALLEL__' + i, false));
  child = start(f);
  await Promise.all(
    tasks.map((t) => waitTask(t.id, (x) => x.turns[0].status === 'review')),
  );
  let auto;
  for (let i = 0; i < 240; i++) {
    auto = (await api('/api/tasks', null, 'GET')).tasks.find(
      (t) => t.autoGenerated && t.repoPath === f.bin,
    );
    if (auto?.turns[0].status === 'review') break;
    await new Promise((r) => setTimeout(r, 300));
  }
  assert.ok(
    auto?.turns[0]?.review,
    'automatic replenishment failed: ' + f.errors,
  );
  const starts = calls(f).filter(
      (e) => e.name === 'claude' && e.event === 'start',
    ),
    ends = calls(f).filter((e) => e.name === 'claude' && e.event === 'end');
  assert.equal(starts.length, 4);
  assert.equal(ends.length, 4);
  let active = 0,
    maximum = 0;
  for (const e of calls(f).filter((e) => e.name === 'claude')) {
    active += e.event === 'start' ? 1 : -1;
    maximum = Math.max(maximum, active);
  }
  assert.ok(
    maximum >= 2 && maximum <= 3,
    'parallel capacity must allow overlapping isolated projects without exceeding 3',
  );
  const taskRecords = (await api('/api/tasks', null, 'GET')).tasks.filter((t) =>
    tasks.some((x) => x.id === t.id),
  );
  assert.equal(new Set(taskRecords.map((t) => t.workDir)).size, 3);
  assert.equal(new Set(taskRecords.map((t) => t.container.name)).size, 3);
  assert.equal(calls(f).filter((e) => e.name === 'generate').length, 1);
  console.log(
    'Docker scheduling: three isolated projects and one automatic replenishment passed',
  );
} finally {
  await stop(child);
  await api('/api/scheduler', original);
}
