import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  capacityFor,
  fingerprint,
  supplyDecision,
} from '../scripts/scheduler.mjs';
test('M1 Pro resource admission reserves memory and reduces new starts under load', () => {
  const m = { cores: 10, totalGB: 32, availableGB: 14, load: 3 };
  assert.equal(capacityFor(m).recommended, 3);
  assert.equal(capacityFor(m).effective, 3);
  assert.equal(capacityFor({ ...m, load: 10 }).effective, 2);
  assert.equal(capacityFor({ ...m, load: 13 }).effective, 1);
  assert.equal(capacityFor({ ...m, availableGB: 4 }).effective, 1);
  assert.equal(capacityFor(m, 1).effective, 1);
});
test('supply waits for sources, queue, budget, cooldown and repeated execution failures', () => {
  const c = {
    config: { enabled: true, dailyLimit: 20 },
    repos: ['/repo'],
    queued: false,
    generatedToday: 0,
    history: [],
  };
  assert.equal(supplyDecision(c, {}), null);
  for (const changed of [
    { repos: [] },
    { queued: true },
    { generatedToday: 20 },
    { config: { enabled: false } },
    { history: Array(3).fill({ autoGenerated: true, failed: true }) },
  ])
    assert.ok(supplyDecision({ ...c, ...changed }, {}));
  assert.ok(supplyDecision(c, { nextAt: 100 }, 50));
  assert.equal(supplyDecision(c, { nextAt: 100 }, 101), null);
});
test('task fingerprint survives punctuation and spacing but keeps repository identity', () => {
  assert.equal(
    fingerprint('/repo/', 'Hello， World!'),
    fingerprint('/repo', 'hello world'),
  );
  assert.notEqual(fingerprint('/a', 'goal'), fingerprint('/b', 'goal'));
});
