import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { parseTask, serializeTask } from '../lib/task-storage.mjs';

function fixture() {
  return {
    id: 'long-project',
    autoGenerated: { fingerprint: 'original-fingerprint' },
    turns: [
      {
        id: 'first',
        status: 'review',
        prompt: '原题\n保留换行、引号"和空白 ',
        review: { source: 'codex', scores: [3, 4, 5, 4, 4] },
        automation: { evidence: '完整历史，不能删除或改写。\n'.repeat(70000) },
        tracePath: '/original/projects/session.jsonl',
        humanReview: { attested: false, notes: '尚未确认' },
      },
      { id: 'second', status: 'running', jobToken: 'fixture-only' },
      { id: 'third', status: 'queued' },
    ],
  };
}

test('large history crosses the D1 row limit and round-trips all fields exactly', () => {
  const task = fixture(),
    json = JSON.stringify(task);
  assert.ok(Buffer.byteLength(json) > 2 * 1024 * 1024);
  const stored = serializeTask(task);
  assert.ok(Buffer.byteLength(stored) < 1800 * 1024);
  assert.equal(JSON.stringify(parseTask(stored)), json);
  assert.equal(JSON.stringify(task), json, 'encoding must not mutate input');
  assert.equal(serializeTask(task), stored);
});

test('legacy JSON stays readable and small tasks retain their storage shape', () => {
  const task = { id: 'small', turns: [{ id: 'one', status: 'queued' }] };
  assert.equal(serializeTask(task), JSON.stringify(task));
  assert.deepEqual(parseTask(JSON.stringify(task)), task);
});

test('atomic queue, source filters, fingerprint and revision guards work across encodings', () => {
  const db = new DatabaseSync(':memory:');
  try {
    db.exec(
      'CREATE TABLE tasks(id TEXT PRIMARY KEY,data TEXT CHECK(length(CAST(data AS BLOB)) < 2097152),revision INTEGER DEFAULT 0)',
    );
    const task = fixture();
    assert.throws(() =>
      db
        .prepare('INSERT INTO tasks(id,data) VALUES(?,?)')
        .run(task.id, JSON.stringify(task)),
    );
    db.prepare('INSERT INTO tasks(id,data) VALUES(?,?)').run(
      task.id,
      serializeTask(task),
    );
    const counts = db
      .prepare(
        "SELECT sum(json_extract(r.value,'$.status')='running') running,sum(json_extract(r.value,'$.status')='queued') queued,sum(json_extract(r.value,'$.review.source')='codex') scored,sum(json_extract(r.value,'$.humanReview') IS NOT NULL) human FROM tasks,json_each(tasks.data,'$.turns') r",
      )
      .get();
    assert.deepEqual(
      { ...counts },
      { running: 1, queued: 1, scored: 1, human: 1 },
    );
    assert.equal(
      db
        .prepare(
          "SELECT json_extract(data,'$.autoGenerated.fingerprint') fingerprint FROM tasks",
        )
        .get().fingerprint,
      task.autoGenerated.fingerprint,
    );
    const restored = parseTask(db.prepare('SELECT data FROM tasks').get().data);
    restored.turns[1].status = 'review';
    const update = db.prepare(
      'UPDATE tasks SET data=?,revision=revision+1 WHERE id=? AND revision=?',
    );
    assert.equal(update.run(serializeTask(restored), task.id, 0).changes, 1);
    assert.equal(update.run(serializeTask(task), task.id, 0).changes, 0);
    assert.deepEqual(
      parseTask(db.prepare('SELECT data FROM tasks').get().data),
      restored,
    );
  } finally {
    db.close();
  }
});

test('corrupt storage, wrong lengths and inconsistent query indexes fail closed', () => {
  const stored = JSON.parse(serializeTask(fixture()));
  assert.throws(
    () => parseTask(JSON.stringify({ ...stored, bytes: stored.bytes - 1 })),
    /长度/,
  );
  assert.throws(
    () => parseTask(JSON.stringify({ ...stored, bytes: 33 * 1024 * 1024 })),
    /格式/,
  );
  assert.throws(() =>
    parseTask(JSON.stringify({ ...stored, payload: 'invalid' })),
  );
  stored.turns[1].status = 'queued';
  assert.throws(() => parseTask(JSON.stringify(stored)), /索引/);
});
