import {
  humanIssues,
  humanAsReview,
  type HumanReview,
  type EvidenceItem,
} from './human-review.ts';
import type { RecordMetadata } from './record-metadata.ts';
export const categories = [
  '0-1 代码生成',
  'Feature 迭代',
  'Bug 修复',
  '代码理解',
  '代码重构',
  '工程化',
  '代码测试',
] as const;
export const difficulties = ['简单', '中等', '困难', '地狱'] as const;
export const dimensions = [
  '交付完整性',
  '指令遵循',
  '任务规划',
  '推理能力',
  '执行能力',
] as const;
export type Review = {
  source?: 'human' | 'codex';
  scores: number[];
  descriptions: string[];
  reviewer: string;
  attested: boolean;
  other: string;
  when?: string[];
  behavior?: string[];
  impact?: string[];
  expected?: string[];
  evidenceRefs?: string[];
  evidenceVerified?: boolean;
  processFindings?: string;
  artifactFindings?: string;
};
export type Turn = {
  roundNumber?: number;
  harness?: 'Claude Code' | 'Codex CLI';
  contextCheck?: any;
  recordMetadata?: RecordMetadata;
  metadataHistory?: {
    at: string;
    previous: RecordMetadata;
    value: RecordMetadata;
  }[];
  id: string;
  prompt: string;
  category: string;
  difficulty: string;
  status: 'queued' | 'running' | 'review' | 'failed' | 'submitted';
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  sessionId?: string;
  promptId?: string;
  output?: string;
  tracePath?: string;
  error?: string;
  review?: Review;
  humanReview?: HumanReview;
  evidence?: EvidenceItem[];
  submittedAt?: string;
  receipt?: string;
  submitter?: string;
  claudeAttempts?: string[];
  excluded?: boolean;
  excludeReason?: string;
  jobToken?: string;
  completedJobToken?: string;
  recoveryToken?: string;
  recoveryBlocked?: boolean;
  stack?: string;
  harnessVersion?: string;
  os?: string;
  model?: string;
  autoFollowup?: boolean;
  stage?: string;
  requestedPrompt?: string;
  continuationOf?: string;
  planRetry?: boolean;
  evaluationPrompt?: string;
  executionOutcome?: 'complete' | 'truncated' | 'error';
  automation?: {
    preparation?: any;
    policy?: any;
    snapshot?: any;
    score?: any;
    delivery?: any;
    bundlePath?: string;
    archive?: { archivePath: string; sha256: string; files: number };
    workflowVersion?: string;
    next?: any;
    nextError?: string;
    evidenceVersion?: number;
  };
};
export type Task = {
  harness?: 'Claude Code' | 'Codex CLI';
  id: string;
  title: string;
  repoPath: string;
  stack: string;
  category: string;
  difficulty: string;
  reproducibility: string;
  snapshot: string;
  githubSnapshot?: {
    url: string;
    sha: string;
    repository: string;
    isPrivate: boolean;
    viewerPermission: string;
    defaultBranch: string;
    verifiedAt: string;
    engine: string;
    accessNote: string;
  };
  sessionId?: string;
  workDir?: string;
  harnessVersion?: string;
  os?: string;
  model?: string;
  createdAt: string;
  closed: boolean;
  automationNotice?: string;
  turns: Turn[];
  automationMode?: 'codex';
  projectSeries?: { version: string; directory: string };
  autoGenerated?: {
    fingerprint: string;
    tracePath: string;
    generatedAt: string;
    policyAudit?: any;
  };
};
export function counted(t: Task) {
  return t.turns.length;
}
export function pending(t: Task) {
  return t.turns.some(
    (x) => x.recoveryBlocked || ['queued', 'running'].includes(x.status),
  );
}
export function validSnapshot(s: string) {
  return /^https:\/\/github\.com\/[^/\s]+\/[^/\s]+\/commit\/[0-9a-f]{40}$/i.test(
    s,
  );
}
export function producedAt(r: Turn) {
  return r.finishedAt || r.startedAt || r.createdAt;
}
export function businessDate(s: string) {
  return new Date(new Date(s).getTime() + 8 * 3600000)
    .toISOString()
    .slice(0, 10);
}
export function deadline(createdAt: string) {
  const date = new Date(new Date(createdAt).getTime() + 8 * 3600000);
  const after = date.getUTCHours() >= 20;
  date.setUTCDate(date.getUTCDate() + (after ? 1 : 0));
  date.setUTCHours(
    after ? 14 : 23,
    after ? 0 : 59,
    after ? 0 : 59,
    after ? 0 : 999,
  );
  return new Date(date.getTime() - 8 * 3600000).toISOString();
}
export function issues(t: Task, r: Turn) {
  const e: string[] = [];
  if (r.excluded) return ['该轮已按工程故障排除'];
  if (r.contextCheck && !r.contextCheck.ready) e.push('上下文配置未通过核验');
  if (!['review', 'submitted'].includes(r.status)) e.push('该轮尚未完成执行');
  if (!validSnapshot(t.snapshot))
    e.push('缺少完整 40 位 SHA 的 GitHub 快照链接');
  if (!t.harnessVersion || !t.os) e.push('缺少客户端版本或操作系统');
  if (!r.sessionId || !r.promptId)
    e.push('缺少 SessionID 或原始用户消息 PromptID');
  if (!r.tracePath) e.push('缺少轨迹文件位置');
  if (!r.review?.reviewer.trim()) e.push('未填写评分人');
  if (r.review?.source === 'codex') {
    if (r.automation?.workflowVersion && !r.automation.archive)
      e.push('证据归档尚未完成');
    if (!r.automation?.delivery?.value?.passed || !r.automation?.bundlePath)
      e.push('Codex 校验或交付包尚未完成');
  } else if (!r.review?.attested) e.push('未确认人工检查过程和产物');
  dimensions.forEach((d, i) => {
    if (
      !Number.isInteger(r.review?.scores[i]) ||
      r.review!.scores[i] < 1 ||
      r.review!.scores[i] > 5
    )
      e.push(`${d}：需填写 1–5 分`);
    if (!r.review?.descriptions[i]?.trim()) e.push(`${d}：需填写具体依据`);
  });
  return e;
}
export function status(t: Task) {
  if (pending(t))
    return t.turns.some((x) => x.status === 'running') ? '执行中' : '排队中';
  if (t.closed) return '已结束';
  if (t.turns.some((x) => x.status === 'failed' && !x.excluded))
    return '执行异常';
  if (
    t.turns.some(
      (x) => x.status === 'review' && !x.excluded && issues(t, x).length,
    )
  )
    return '待评分或校验';
  if (t.turns.some((x) => x.status === 'review' && !x.excluded))
    return '待提交';
  return t.turns.length ? '可继续交互' : '待开始';
}
export function csv(tasks: Task[], source: 'primary' | 'human' = 'primary') {
  const headers = [
    '任务名称',
    '任务类型',
    '任务难度',
    '语言/框架',
    'Harness',
    'Harness 版本',
    '操作系统',
    '环境可复现等级',
    '初始环境快照',
    'User Prompt',
    'SessionID',
    'TurnID/PromptID',
    '轨迹文件',
    ...dimensions.flatMap((d) => [d, d + ' - 描述']),
    '其他问题',
    '评分人',
    '评分来源',
    '数据用途',
    '产生时间',
    '提交截止时间',
  ];
  const rows = tasks.flatMap((t) =>
    t.turns
      .filter(
        (r) =>
          !r.excluded &&
          !(source === 'human' ? humanIssues(t, r) : issues(t, r)).length,
      )
      .map((original) => {
        const manual = source === 'human';
        const r = manual
          ? { ...original, review: humanAsReview(original.humanReview!) }
          : original;
        return [
          t.title,
          r.category,
          r.difficulty,
          r.stack || t.stack,
          r.harness || t.harness || 'Claude Code',
          r.harnessVersion || t.harnessVersion,
          r.os || t.os,
          t.reproducibility,
          t.snapshot,
          r.prompt,
          r.sessionId,
          r.promptId,
          r.tracePath,
          ...dimensions.flatMap((_, i) => [
            r.review!.scores[i],
            r.review!.descriptions[i],
          ]),
          r.review!.other,
          r.review!.reviewer,
          manual
            ? '人工复核（已有 AI 评估）'
            : r.review!.source === 'codex'
              ? 'AI / Codex CLI'
              : '人工',
          manual
            ? '人工复核数据，非纯人工标注流程'
            : r.review!.source === 'codex'
              ? 'AI评测数据（不作为原项目人工标注）'
              : '人工标注',
          producedAt(r),
          deadline(producedAt(r)),
        ];
      }),
  );
  const cell = (x: unknown) =>
    '"' +
    String(x ?? '')
      .replace(/^[=+@\-\t\r]/, (m) => "'" + m)
      .replace(/"/g, '""') +
    '"';
  return (
    '\ufeff' +
    [headers, ...rows].map((row) => row.map(cell).join(',')).join('\r\n')
  );
}
