export type SchedulerConfig = {
  enabled: boolean;
  autoContinue: boolean;
  useHistory: boolean;
  repos: string[];
  scope: string;
  concurrency: number;
  dailyLimit: number;
};
export const defaultScheduler: SchedulerConfig = {
  enabled: true,
  autoContinue: true,
  useHistory: true,
  repos: [],
  scope:
    '设计中等或困难的独立项目，首题从 0-1 创建可运行基础项目，再在同一项目生成有价值的功能迭代、真实缺陷修复、理解与重构题。不同项目互相独立。',
  concurrency: 3,
  dailyLimit: 20,
};
export function normalizeConfig(b: any): SchedulerConfig {
  if (typeof b.enabled !== 'boolean' || typeof b.useHistory !== 'boolean')
    throw Error('补充开关无效');
  if (
    !Number.isInteger(b.concurrency) ||
    b.concurrency < 1 ||
    b.concurrency > 4
  )
    throw Error('并发上限须为 1–4');
  if (!Number.isInteger(b.dailyLimit) || b.dailyLimit < 1 || b.dailyLimit > 100)
    throw Error('每日补充上限须为 1–100');
  if (
    !Array.isArray(b.repos) ||
    b.repos.length > 20 ||
    b.repos.some(
      (p: unknown) =>
        typeof p !== 'string' || !p.startsWith('/') || p.length > 2000,
    )
  )
    throw Error('请填写本机仓库绝对路径，最多 20 个');
  if (typeof b.scope !== 'string' || !b.scope.trim() || b.scope.length > 4000)
    throw Error('出题范围不能为空或超过 4000 字');
  if (b.autoContinue !== undefined && typeof b.autoContinue !== 'boolean')
    throw Error('自动续跑开关无效');
  return {
    enabled: b.enabled,
    autoContinue: b.autoContinue ?? true,
    useHistory: b.useHistory,
    repos: [
      ...new Set<string>(
        b.repos.map((p: string) => p.trim().replace(/\/+$/, '') || '/'),
      ),
    ],
    scope: b.scope.trim(),
    concurrency: b.concurrency,
    dailyLimit: b.dailyLimit,
  };
}
export function sources(config: SchedulerConfig, tasks: any[]): string[] {
  return [
    ...new Set([
      ...config.repos,
      ...(config.useHistory
        ? tasks.filter((t) => !t.autoGenerated).map((t) => t.repoPath)
        : []),
    ]),
  ];
}
