import { gzipSync, gunzipSync, strToU8, strFromU8 } from 'fflate';

// D1 limits a row to 2 MiB. Keep the complete task losslessly compressed and
// retain the small JSON fields used by atomic queue/claim and record queries.
// This is database encoding only; it never rewrites a trajectory or export.
const marker = '__annotationTaskStorage';
const threshold = 384 * 1024;
const maxDecodedBytes = 32 * 1024 * 1024;
const maxStoredBytes = 1800 * 1024;

function index(task) {
  return {
    id: task.id,
    ...(task.autoGenerated != null
      ? { autoGenerated: task.autoGenerated }
      : {}),
    turns: task.turns.map((r) => ({
      id: r.id,
      status: r.status,
      ...(r.review != null ? { review: { source: r.review.source } } : {}),
      ...(r.humanReview != null ? { humanReview: true } : {}),
    })),
  };
}

export function serializeTask(task) {
  const json = JSON.stringify(task);
  const bytes = strToU8(json);
  if (bytes.length < threshold) return json;
  if (bytes.length > maxDecodedBytes)
    throw Error('任务历史超过存储容量，完整结果已保留，不能裁剪后回写');
  const compressed = gzipSync(bytes, { level: 6, mtime: 0 });
  let binary = '';
  for (let offset = 0; offset < compressed.length; offset += 8192)
    binary += String.fromCharCode(
      ...compressed.subarray(offset, offset + 8192),
    );
  const stored = JSON.stringify({
    [marker]: 1,
    encoding: 'gzip-base64',
    bytes: bytes.length,
    payload: btoa(binary),
    ...index(task),
  });
  if (strToU8(stored).length > maxStoredBytes)
    throw Error('任务历史压缩后仍超过数据库容量，完整结果已保留');
  return stored;
}

export function parseTask(data) {
  const stored = JSON.parse(data);
  if (!Object.hasOwn(stored, marker)) return stored;
  if (
    stored[marker] !== 1 ||
    stored.encoding !== 'gzip-base64' ||
    !Number.isSafeInteger(stored.bytes) ||
    stored.bytes < 1 ||
    stored.bytes > maxDecodedBytes ||
    typeof stored.payload !== 'string' ||
    stored.payload.length > maxStoredBytes
  )
    throw Error('任务存储格式无效');
  const binary = atob(stored.payload);
  const compressed = Uint8Array.from(binary, (c) => c.charCodeAt(0));
  if (
    compressed.length < 18 ||
    new DataView(compressed.buffer).getUint32(compressed.length - 4, true) !==
      stored.bytes
  )
    throw Error('任务存储长度校验失败');
  const bytes = gunzipSync(compressed, new Uint8Array(stored.bytes));
  if (bytes.length !== stored.bytes) throw Error('任务存储长度校验失败');
  const task = JSON.parse(strFromU8(bytes));
  if (JSON.stringify(index(task)) !== JSON.stringify(index(stored)))
    throw Error('任务存储索引与完整记录不一致');
  return task;
}
