import { schedulerConfig } from '@/db/scheduler';
import { sources } from '@/lib/scheduler';
import {
  categories,
  difficulties,
  businessDate,
  type Task,
} from '@/lib/pipeline';
import { all, get, save, db, failure, runnerAuth, text } from '@/db/store';
export async function POST(req: Request) {
  try {
    runnerAuth(req);
    const b: any = await req.json();
    if (!b || typeof b !== 'object' || Array.isArray(b))
      throw new Error('请求格式无效');
    if (b.action === 'heartbeat') {
      await db()
        .prepare(
          'INSERT INTO runners(id,data,heartbeat) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,heartbeat=excluded.heartbeat',
        )
        .bind(
          'local',
          JSON.stringify({
            version: text(b.version, '版本', 200),
            mode: 'Codex 编排 / Claude 执行',
            scheduler:
              b.scheduler && typeof b.scheduler === 'object'
                ? b.scheduler
                : null,
            codexVersion:
              typeof b.codexVersion === 'string' ? b.codexVersion : '',
          }),
          new Date().toISOString(),
        )
        .run();
      return Response.json({ ok: true });
    }
    if (b.action === 'supply-context') {
      const tasks = await all(),
        config = await schedulerConfig();
      return Response.json({
        config,
        repos: sources(config, tasks),
        queued: tasks.some((t) =>
          t.turns.some((r: any) => r.status === 'queued'),
        ),
        generatedToday: tasks.filter(
          (t) =>
            t.autoGenerated &&
            businessDate(t.createdAt) ===
              businessDate(new Date().toISOString()),
        ).length,
        history: tasks.map((t) => ({
          id: t.id,
          title: t.title,
          repoPath: t.repoPath,
          autoGenerated: !!t.autoGenerated,
          failed: t.turns.some((r: any) => r.status === 'failed'),
        })),
      });
    }
    if (b.action === 'enqueue-auto') {
      const tasks = await all(),
        config = await schedulerConfig();
      const fingerprint = text(b.fingerprint, '去重标识', 64);
      if (!/^[a-f0-9]{64}$/.test(fingerprint)) throw Error('去重标识无效');
      const existing = tasks.find(
        (t) => t.autoGenerated?.fingerprint === fingerprint,
      );
      if (existing)
        return Response.json({ taskId: existing.id, duplicate: true });
      if (!config.enabled) return Response.json({ skipped: '自动补充已暂停' });
      if (!sources(config, tasks).includes(b.repoPath))
        throw Error('仓库不在自动补充范围内');
      if (
        !categories.includes(b.category) ||
        !difficulties.includes(b.difficulty) ||
        b.difficulty === '简单'
      )
        throw Error('自动题型或难度无效');
      const now = new Date().toISOString(),
        day = businessDate(now);
      const task: Task = {
        id: crypto.randomUUID(),
        title: text(b.title, '任务名称', 200),
        repoPath: text(b.repoPath, '仓库', 2000),
        stack: text(b.stack, '技术栈', 300),
        category: b.category,
        difficulty: b.difficulty,
        reproducibility: '待 Codex 环境检查',
        snapshot: '',
        createdAt: now,
        closed: false,
        automationMode: 'codex',
        autoGenerated: {
          fingerprint,
          tracePath: text(b.tracePath, '出题轨迹', 4000),
          generatedAt: now,
        },
        turns: [
          {
            id: crypto.randomUUID(),
            prompt: text(b.prompt, '任务目标', 20000),
            category: b.category,
            difficulty: b.difficulty,
            status: 'queued',
            createdAt: now,
          },
        ],
      };
      // One SQL statement guards concurrent replenishment, daily quota and duplicate receipts.
      const inserted = await db()
        .prepare(`INSERT INTO tasks(id,data,created_at) SELECT ?,?,?
        WHERE NOT EXISTS (SELECT 1 FROM tasks,json_each(tasks.data,'$.turns') r WHERE json_extract(r.value,'$.status')='queued')
        AND NOT EXISTS (SELECT 1 FROM tasks WHERE json_extract(data,'$.autoGenerated.fingerprint')=?)
        AND (SELECT count(*) FROM tasks WHERE json_extract(data,'$.autoGenerated') IS NOT NULL AND date(created_at,'+8 hours')=?) < ?
        AND COALESCE((SELECT json_extract(data,'$.enabled') FROM runners WHERE id='scheduler'),1)=1`)
        .bind(
          task.id,
          JSON.stringify(task),
          now,
          fingerprint,
          day,
          config.dailyLimit,
        )
        .run();
      return Response.json(
        inserted.meta.changes
          ? { taskId: task.id }
          : { skipped: '队列已补充或达到每日上限' },
      );
    }
    if (b.action === 'claim') {
      const tasks = await all(),
        config = await schedulerConfig();
      const capacity = Math.min(
        config.concurrency,
        Number.isInteger(b.capacity) ? Math.max(1, Math.min(4, b.capacity)) : 1,
      );
      for (const item of [...tasks].reverse()) {
        if (item.closed || item.turns.some((r: any) => r.status === 'running'))
          continue;
        const r = item.turns.find((r: any) => r.status === 'queued');
        if (!r) continue;
        item.automationMode = 'codex';
        r.status = 'running';
        r.startedAt = new Date().toISOString();
        r.jobToken = crypto.randomUUID();
        const { revision, ...task } = item;
        // Revision CAS and global running count are checked atomically, including simultaneous claims.
        const claimed = await db()
          .prepare(`UPDATE tasks SET data=?,revision=revision+1 WHERE id=? AND revision=?
          AND (SELECT count(*) FROM tasks,json_each(tasks.data,'$.turns') r WHERE json_extract(r.value,'$.status')='running') < ?`)
          .bind(JSON.stringify(task), task.id, revision, capacity)
          .run();
        if (claimed.meta.changes)
          return Response.json({ job: { task, turn: r } });
      }
      return Response.json({ job: null });
    }
    if (b.action === 'stage') {
      const item = await get(text(b.taskId, '任务 ID'));
      const r = item?.task.turns.find((r) => r.id === b.turnId);
      if (!item || !r || r.status !== 'running' || r.jobToken !== b.jobToken)
        throw new Error('阶段更新凭据错误');
      if (
        !['prepare', 'snapshot', 'claude', 'score', 'delivery'].includes(
          b.stage,
        )
      )
        throw new Error('未知阶段');
      r.stage = b.stage;
      await save(item.task, item.revision);
      return Response.json({ ok: true });
    }
    if (b.action === 'finish') {
      const item = await get(text(b.taskId, '任务 ID'));
      if (!item) throw new Error('任务不存在');
      const r = item.task.turns.find((r) => r.id === b.turnId);
      if (typeof b.jobToken === 'string' && r?.completedJobToken === b.jobToken)
        return Response.json({ ok: true });
      if (!r || r.status !== 'running' || r.jobToken !== b.jobToken)
        throw new Error('任务状态或执行凭据不匹配');
      r.status = b.success ? 'review' : 'failed';
      r.finishedAt =
        typeof b.finishedAt === 'string' && !isNaN(Date.parse(b.finishedAt))
          ? b.finishedAt
          : new Date().toISOString();
      if (b.automation && typeof b.automation === 'object')
        r.automation = b.automation;
      if (typeof b.stage === 'string') r.stage = b.stage;
      if (b.preparedPrompt) {
        r.requestedPrompt = r.requestedPrompt || r.prompt;
        r.prompt = text(b.preparedPrompt, 'Codex Prompt', 80000);
      }
      if (b.review?.source === 'codex') {
        const v = b.review;
        if (
          !Array.isArray(v.scores) ||
          v.scores.length !== 5 ||
          v.scores.some((x: any) => !Number.isInteger(x) || x < 1 || x > 5) ||
          !Array.isArray(v.descriptions) ||
          v.descriptions.length !== 5 ||
          v.descriptions.some((x: any) => typeof x !== 'string' || !x.trim())
        )
          throw new Error('Codex 评分无效');
        r.review = {
          ...v,
          source: 'codex',
          attested: false,
          reviewer: 'Codex CLI（AI）',
        };
      }
      if (b.preparation) {
        item.task.category = b.preparation.category;
        item.task.difficulty = b.preparation.difficulty;
        item.task.stack = b.preparation.stack;
        r.category = b.preparation.category;
        r.difficulty = b.preparation.difficulty;
      }
      r.sessionId = typeof b.sessionId === 'string' ? b.sessionId : undefined;
      r.promptId = typeof b.promptId === 'string' ? b.promptId : undefined;
      r.output = String(b.output || '').slice(0, 100000);
      r.error = String(b.error || '').slice(0, 10000);
      r.tracePath = String(b.tracePath || '');
      r.completedJobToken = r.jobToken;
      delete r.jobToken;
      for (const key of [
        'workDir',
        'harnessVersion',
        'os',
        'model',
        'sessionId',
      ] as const)
        if (typeof b[key] === 'string') item.task[key] = b[key];
      if (!item.task.snapshot && typeof b.snapshot === 'string')
        item.task.snapshot = b.snapshot;
      await save(item.task, item.revision);
      return Response.json({ ok: true });
    }
    throw new Error('未知执行器操作');
  } catch (e) {
    return failure(e);
  }
}
