import { validateSeries, claudeCallCount } from '@/lib/project-series.mjs';
import { validateContainerRecord } from '@/lib/container-policy.mjs';
import { questionRoot } from '@/lib/question-session.mjs';
import { permissionIssues } from '@/lib/permission-audit.mjs';
import { roundNumber } from '@/lib/record-metadata';
import { nextDecision, dailyMix } from '@/lib/workflow.mjs';
import { candidateDigest, assertPolicyAudit } from '@/lib/task-policy.mjs';
import { schedulerConfig } from '@/db/scheduler';
import { sources } from '@/lib/scheduler';
import {
  categories,
  difficulties,
  businessDate,
  type Task,
  type Turn,
} from '@/lib/pipeline';
import { all, get, save, db, failure, runnerAuth, text } from '@/db/store';
export async function POST(req: Request) {
  try {
    runnerAuth(req);
    const b: any = await req.json();
    if (!b || typeof b !== 'object' || Array.isArray(b))
      throw new Error('请求格式无效');
    if (b.action === 'heartbeat') {
      await db()
        .prepare(
          'INSERT INTO runners(id,data,heartbeat) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,heartbeat=excluded.heartbeat',
        )
        .bind(
          'local',
          JSON.stringify({
            version: text(b.version, '版本', 200),
            mode: 'Codex 编排 / Claude 执行',
            github: b.github && typeof b.github === 'object' ? b.github : null,
            scheduler:
              b.scheduler && typeof b.scheduler === 'object'
                ? b.scheduler
                : null,
            codexVersion:
              typeof b.codexVersion === 'string' ? b.codexVersion : '',
          }),
          new Date().toISOString(),
        )
        .run();
      return Response.json({ ok: true });
    }
    if (b.action === 'supply-context') {
      const tasks = await all(),
        config = await schedulerConfig();
      return Response.json({
        config,
        mix: dailyMix(tasks, businessDate(new Date().toISOString())),
        repos: sources(config, tasks),
        containerTasks: tasks
          .filter((t) => t.container)
          .map((t) => ({
            id: t.id,
            containerStatus: t.container.status,
            closed: t.closed,
            finishContainer:
              !t.turns.some((r: Turn) =>
                ['queued', 'running'].includes(r.status),
              ) &&
              (claudeCallCount(t) >= 10 ||
                ['complete', 'needs_input'].includes(
                  t.turns.at(-1)?.automation?.next?.value?.action,
                )),
          })),
        queued: tasks.some((t) =>
          t.turns.some((r: any) => r.status === 'queued'),
        ),
        generatedToday: tasks.filter(
          (t) =>
            t.autoGenerated &&
            businessDate(t.createdAt) ===
              businessDate(new Date().toISOString()),
        ).length,
        history: tasks.map((t) => ({
          id: t.id,
          title: t.title,
          prompt: t.turns
            .map((r: any) => r.requestedPrompt || r.prompt)
            .join('\n')
            .slice(0, 4000),
          repoPath: t.repoPath,
          autoGenerated: !!t.autoGenerated,
          failed: t.turns.some((r: any) => r.status === 'failed'),
        })),
      });
    }
    if (b.action === 'enqueue-auto') {
      const tasks = await all(),
        config = await schedulerConfig();
      const fingerprint = text(b.fingerprint, '去重标识', 64);
      if (!/^[a-f0-9]{64}$/.test(fingerprint)) throw Error('去重标识无效');
      const existing = tasks.find(
        (t) => t.autoGenerated?.fingerprint === fingerprint,
      );
      if (existing)
        return Response.json({ taskId: existing.id, duplicate: true });
      if (!config.enabled) return Response.json({ skipped: '自动补充已暂停' });
      if (!sources(config, tasks).includes(b.repoPath))
        throw Error('仓库不在自动补充范围内');
      if (
        !categories.includes(b.category) ||
        !difficulties.includes(b.difficulty) ||
        b.difficulty === '简单'
      )
        throw Error('自动题型或难度无效');
      validateSeries(b.projectSeries);
      if (b.category !== '0-1 代码生成')
        throw Error('自动新项目首题必须为 0-1 代码生成');
      assertPolicyAudit(b.policyAudit, await candidateDigest(b));
      if (b.difficulty !== b.policyAudit.value.assessedDifficulty)
        throw Error('题目难度与独立审核等级不一致');
      const now = new Date().toISOString(),
        day = businessDate(now);
      const task: Task = {
        projectSeries: b.projectSeries,
        id: crypto.randomUUID(),
        title: text(b.title, '任务名称', 200),
        repoPath: text(b.repoPath, '仓库', 2000),
        stack: text(b.stack, '技术栈', 300),
        category: b.category,
        difficulty: b.difficulty,
        reproducibility: '待 Codex 环境检查',
        snapshot: '',
        createdAt: now,
        closed: false,
        automationMode: 'codex',
        autoGenerated: {
          fingerprint,
          tracePath: text(b.tracePath, '出题轨迹', 4000),
          generatedAt: now,
          policyAudit: b.policyAudit,
        },
        turns: [
          {
            id: crypto.randomUUID(),
            roundNumber: 1,
            prompt: text(b.prompt, '任务目标', 20000),
            category: b.category,
            difficulty: b.difficulty,
            status: 'queued',
            createdAt: now,
          },
        ],
      };
      task.turns[0].questionRootId = task.turns[0].id;
      // One SQL statement guards concurrent replenishment, daily quota and duplicate receipts.
      const inserted = await db()
        .prepare(`INSERT INTO tasks(id,data,created_at) SELECT ?,?,?
        WHERE NOT EXISTS (SELECT 1 FROM tasks,json_each(tasks.data,'$.turns') r WHERE json_extract(r.value,'$.status')='queued')
        AND NOT EXISTS (SELECT 1 FROM tasks WHERE json_extract(data,'$.autoGenerated.fingerprint')=?)
        AND (SELECT count(*) FROM tasks WHERE json_extract(data,'$.autoGenerated') IS NOT NULL AND date(created_at,'+8 hours')=?) < ?
        AND COALESCE((SELECT json_extract(data,'$.enabled') FROM runners WHERE id='scheduler'),1)=1`)
        .bind(
          task.id,
          JSON.stringify(task),
          now,
          fingerprint,
          day,
          config.dailyLimit,
        )
        .run();
      return Response.json(
        inserted.meta.changes
          ? { taskId: task.id }
          : { skipped: '队列已补充或达到每日上限' },
      );
    }
    if (b.action === 'claim') {
      const tasks = await all(),
        config = await schedulerConfig();
      const capacity = Math.min(
        config.concurrency,
        Number.isInteger(b.capacity) ? Math.max(1, Math.min(4, b.capacity)) : 1,
      );
      const residents = Array.isArray(b.residentTaskIds)
        ? b.residentTaskIds
        : [];
      const ordered = [...tasks]
        .reverse()
        .sort(
          (a, b) =>
            Number(residents.includes(b.id)) - Number(residents.includes(a.id)),
        );
      for (const item of ordered) {
        if (b.allowNewContainer === false && !residents.includes(item.id))
          continue;
        if (
          item.closed ||
          item.turns.some(
            (r: any) => r.recoveryBlocked || r.status === 'running',
          )
        )
          continue;
        const r = item.turns.find((r: any) => r.status === 'queued');
        if (!r) continue;
        r.questionRootId ||= questionRoot(item, r);
        r.roundNumber = item.turns
          .slice(0, item.turns.indexOf(r) + 1)
          .filter(
            (x: Turn) => questionRoot(item, x) === r.questionRootId,
          ).length;
        item.automationMode = 'codex';
        r.status = 'running';
        r.startedAt = new Date().toISOString();
        r.jobToken = crypto.randomUUID();
        const { revision, ...task } = item;
        // Revision CAS and global running count are checked atomically, including simultaneous claims.
        const claimed = await db()
          .prepare(`UPDATE tasks SET data=?,revision=revision+1 WHERE id=? AND revision=?
          AND (SELECT count(*) FROM tasks,json_each(tasks.data,'$.turns') r WHERE json_extract(r.value,'$.status')='running') < ?`)
          .bind(JSON.stringify(task), task.id, revision, capacity)
          .run();
        if (claimed.meta.changes)
          return Response.json({ job: { task, turn: r } });
      }
      return Response.json({ job: null });
    }
    if (b.action === 'reserve-claude') {
      const item = await get(text(b.taskId, '任务 ID'));
      const r = item?.task.turns.find((r) => r.id === b.turnId);
      if (!item || !r || r.status !== 'running' || r.jobToken !== b.jobToken)
        throw Error('执行额度凭据无效');
      const attempt = text(b.attemptId, '调用标识', 200);
      const sessionId = b.sessionId
        ? text(b.sessionId, 'Claude 会话 ID', 300)
        : undefined;
      if (!sessionId && (!item.task.container || item.task.sessionId))
        throw Error('缺少现有会话 ID 或新容器记录');
      if (item.task.sessionId && item.task.sessionId !== sessionId)
        throw Error('不能在同一项目切换 Claude 会话');
      if (r.claudeAttempts?.includes(attempt))
        return Response.json({
          allowed: true,
          count: claudeCallCount(item.task),
        });
      r.claudeAttempts ||= r.promptId || r.sessionId ? ['legacy'] : [];
      if (claudeCallCount(item.task) >= 10)
        return Response.json({ allowed: false, count: 10 });
      // Reserve before spawning; even uncertain/failed calls retain their slot.
      r.claudeAttempts.push(attempt);
      if (sessionId) item.task.sessionId = sessionId;
      await save(item.task, item.revision);
      return Response.json({
        allowed: true,
        count: claudeCallCount(item.task),
      });
    }
    if (b.action === 'container') {
      const item = await get(text(b.taskId, '任务 ID'));
      if (!item) throw Error('任务不存在');
      const container = validateContainerRecord(b.container, item.task.id);
      if (item.task.container && item.task.container.name !== container.name)
        throw Error('不能切换任务容器');
      if (item.task.container?.questionId !== container.questionId) {
        if (container.sessionId) item.task.sessionId = container.sessionId;
        else delete item.task.sessionId;
      }
      item.task.container = container;
      item.task.workDir = container.workDir;
      await save(item.task, item.revision);
      return Response.json({ ok: true });
    }
    if (b.action === 'stage') {
      const item = await get(text(b.taskId, '任务 ID'));
      const r = item?.task.turns.find((r) => r.id === b.turnId);
      if (!item || !r || r.status !== 'running' || r.jobToken !== b.jobToken)
        throw new Error('阶段更新凭据错误');
      if (
        ![
          'context',
          'prepare',
          'policy',
          'snapshot',
          'claude',
          'score',
          'delivery',
          'next',
          'project-next',
        ].includes(b.stage)
      )
        throw new Error('未知阶段');
      r.stage = b.stage;
      await save(item.task, item.revision);
      return Response.json({ ok: true });
    }
    if (b.action === 'recover') {
      const item = await get(text(b.taskId, '任务 ID'));
      const r = item?.task.turns.find((r) => r.id === b.turnId);
      if (!item || !r) return Response.json({ done: true });
      if (r.completedJobToken === b.jobToken)
        return Response.json({ done: true });
      if (
        typeof b.jobToken !== 'string' ||
        (r.jobToken !== b.jobToken && r.recoveryToken !== b.jobToken)
      )
        return Response.json({ done: true });
      r.recoveryToken = b.jobToken;
      delete r.jobToken;
      r.status = 'failed';
      r.recoveryBlocked = b.live === true;
      r.error = b.live
        ? '旧执行器子进程仍在运行，暂不允许重试'
        : '执行器中断，结果未确认；请检查轨迹后决定重试或排除';
      if (!b.live && b.salvage?.success === true) {
        r.status = 'queued';
        r.error = '';
        for (const key of [
          'workDir',
          'sessionId',
          'snapshot',
          'harnessVersion',
          'os',
          'model',
        ] as const)
          if (typeof b.salvage[key] === 'string')
            item.task[key] = b.salvage[key];
      }
      if (!b.live) delete r.recoveryToken;
      await save(item.task, item.revision);
      return Response.json({ done: !b.live });
    }
    if (b.action === 'finish') {
      const item = await get(text(b.taskId, '任务 ID'));
      if (!item) throw new Error('任务不存在');
      const r = item.task.turns.find((r) => r.id === b.turnId);
      if (typeof b.jobToken === 'string' && r?.completedJobToken === b.jobToken)
        return Response.json({ ok: true });
      if (!r || r.status !== 'running' || r.jobToken !== b.jobToken)
        throw new Error('任务状态或执行凭据不匹配');
      if (b.success && b.contextCheck && !b.contextCheck.ready)
        throw Error('上下文未通过核验，不能标记执行成功');
      if (b.container) {
        const container = validateContainerRecord(b.container, item.task.id);
        if (item.task.container && item.task.container.name !== container.name)
          throw Error('任务容器发生变化');
        if (b.success && !b.traceExport?.verified)
          throw Error('容器完整轨迹尚未导出核验');
        if (b.success && permissionIssues(b).length)
          throw Error(permissionIssues(b).join('；'));
        if (
          item.task.sessionId &&
          b.sessionId &&
          item.task.sessionId !== b.sessionId
        )
          throw Error('容器 SessionID 发生变化');
        item.task.container = container;
        r.container = container;
        r.traceExport = b.traceExport;
        r.permissionAudit = b.permissionAudit;
      }
      r.status = b.success ? 'review' : 'failed';
      r.roundNumber ||= roundNumber(item.task, r) || undefined;
      if (b.harness !== undefined) {
        if (!['Claude Code', 'Codex CLI'].includes(b.harness))
          throw Error('Harness 无效');
        if (item.task.harness && item.task.harness !== b.harness)
          throw Error('同一会话不能切换 Harness');
        r.harness = b.harness;
        item.task.harness = b.harness;
      }
      if (b.contextCheck && typeof b.contextCheck === 'object')
        r.contextCheck = b.contextCheck;
      if (b.success) delete r.planRetry;
      r.finishedAt =
        typeof b.finishedAt === 'string' && !isNaN(Date.parse(b.finishedAt))
          ? b.finishedAt
          : new Date().toISOString();
      if (b.automation && typeof b.automation === 'object')
        r.automation = b.automation;
      if (
        Array.isArray(b.evidence) &&
        JSON.stringify(b.evidence).length <= 65000 &&
        b.evidence.every(
          (x: any) =>
            x &&
            /^[a-z0-9_-]+$/.test(x.id) &&
            typeof x.label === 'string' &&
            typeof x.content === 'string',
        )
      )
        r.evidence = b.evidence;
      if (typeof b.stage === 'string') r.stage = b.stage;
      if (b.preparedPrompt) {
        r.requestedPrompt = r.requestedPrompt || r.prompt;
        text(b.preparedPrompt, 'Codex Prompt', 80000);
        r.prompt = b.preparedPrompt;
      }
      if (b.review?.source === 'codex') {
        const v = b.review;
        if (
          !Array.isArray(v.scores) ||
          v.scores.length !== 5 ||
          v.scores.some((x: any) => !Number.isInteger(x) || x < 1 || x > 5) ||
          !Array.isArray(v.descriptions) ||
          v.descriptions.length !== 5 ||
          v.descriptions.some((x: any) => typeof x !== 'string' || !x.trim())
        )
          throw new Error('Codex 评分无效');
        r.review = {
          ...v,
          source: 'codex',
          attested: false,
          reviewer: 'Codex CLI（AI）',
        };
      }
      if (b.preparation) {
        item.task.category = b.preparation.category;
        item.task.difficulty = b.preparation.difficulty;
        item.task.stack = b.preparation.stack;
        r.stack = b.preparation.stack;
        r.category = b.preparation.category;
        r.difficulty = b.preparation.difficulty;
      }
      r.sessionId = typeof b.sessionId === 'string' ? b.sessionId : undefined;
      r.promptId = typeof b.promptId === 'string' ? b.promptId : undefined;
      if (typeof b.evaluationPrompt === 'string')
        r.evaluationPrompt = text(b.evaluationPrompt, '原始验收目标', 80000);
      if (['complete', 'truncated', 'error'].includes(b.executionOutcome))
        r.executionOutcome = b.executionOutcome;
      r.output = String(b.output || '').slice(0, 100000);
      r.error = String(b.error || '').slice(0, 10000);
      r.tracePath = String(b.tracePath || '');
      r.completedJobToken = r.jobToken;
      delete r.jobToken;
      for (const key of [
        'workDir',
        'harnessVersion',
        'os',
        'model',
        'sessionId',
      ] as const)
        if (typeof b[key] === 'string') item.task[key] = b[key];
      for (const key of ['harnessVersion', 'os', 'model'] as const)
        if (typeof b[key] === 'string') r[key] = b[key];
      if (
        (!item.task.snapshot || item.task.turns[0]?.id === r.id) &&
        typeof b.reproducibility === 'string'
      )
        item.task.reproducibility = b.reproducibility;
      if (b.githubSnapshot?.engine === 'github-cli')
        item.task.githubSnapshot = b.githubSnapshot;
      if (!item.task.snapshot && typeof b.snapshot === 'string')
        item.task.snapshot = b.snapshot;
      if (b.success && !item.task.closed) {
        let decision;
        try {
          decision = nextDecision(item.task, r, await schedulerConfig());
        } catch (e) {
          r.automation ||= {};
          r.automation.nextError =
            e instanceof Error ? e.message : '后续规划无效';
          delete r.automation.next;
        }
        if (r.automation?.nextError)
          item.task.automationNotice =
            '本轮已归档；后续出题待重试：' + r.automation.nextError;
        if (decision) {
          item.task.automationNotice = decision.notice;
          if (decision.prompt) {
            const id = crypto.randomUUID();
            const continued = 'continuationOf' in decision;
            item.task.turns.push({
              roundNumber: continued ? (r.roundNumber || 1) + 1 : 1,
              questionRootId: continued ? r.questionRootId || r.id : id,
              id,
              prompt: decision.prompt,
              ...('continuationOf' in decision && 'evaluationPrompt' in decision
                ? {
                    continuationOf: String(decision.continuationOf),
                    evaluationPrompt: String(decision.evaluationPrompt),
                  }
                : {}),
              category:
                ('category' in decision && decision.category) || r.category,
              difficulty:
                ('difficulty' in decision && decision.difficulty) ||
                r.difficulty,
              status: 'queued',
              createdAt: new Date().toISOString(),
              autoFollowup: true,
            });
          }
        }
      }
      await save(item.task, item.revision);
      return Response.json({ ok: true });
    }
    throw new Error('未知执行器操作');
  } catch (e) {
    return failure(e);
  }
}
