import { db } from './store';
import {
  recordRow,
  type RecordFilter,
  type RecordRow,
} from '@/lib/record-fields';
import {
  businessRecord,
  businessRecordOrigins,
} from '@/lib/business-record.mjs';
import type { Task } from '@/lib/pipeline';
import type { ExportScope, RecordIdentity } from '@/lib/record-selection';

// Collapse recovery calls before filtering/counting/pagination. Read projects in
// bounded chunks and omit model outputs/diagnostics, rather than loading traces.
export async function selectRecords(
  f: RecordFilter,
  scope: ExportScope = 'page',
  selected: RecordIdentity[] = [],
) {
  const rows: { row: RecordRow; date: string; ordinal: number }[] = [];
  const selection = new Set(selected.map((r) => r.taskId + ':' + r.turnId));
  let cursor = '';
  for (;;) {
    const batch = await db()
      .prepare(`SELECT t.id,
      json_set(json_remove(t.data,'$.turns','$.autoGenerated'),'$.projectName',(SELECT printf('nyh-%05d',sequence) FROM project_names WHERE task_id=t.id)) task,
      (SELECT json_group_array(json(json_remove(r.value,'$.output','$.evidence','$.automation.score','$.automation.next','$.automation.snapshot'))) FROM json_each(t.data,'$.turns') r) turns,
      (SELECT json_group_array(json_object('turnId',turn_id,'batchId',batch_id,'at',created_at)) FROM export_items WHERE task_id=t.id) exports,
      (SELECT data FROM runners WHERE id='solo-upload') upload
      FROM tasks t WHERE t.id>? ${f.projectId ? 'AND t.id=?' : ''}
      AND EXISTS(SELECT 1 FROM json_each(t.data,'$.turns') r WHERE ${f.source === 'human' ? "json_extract(r.value,'$.humanReview') IS NOT NULL" : "json_extract(r.value,'$.review.source')='codex'"})
      ORDER BY t.id LIMIT 20`)
      .bind(cursor, ...(f.projectId ? [f.projectId] : []))
      .all<{
        id: string;
        task: string;
        turns: string;
        exports: string;
        upload: string | null;
      }>();
    if (!batch.results.length) break;
    for (const item of batch.results) {
      const task = {
        ...JSON.parse(item.task),
        turns: JSON.parse(item.turns),
      } as Task;
      const exports = JSON.parse(item.exports) as {
        turnId: string;
        batchId: string;
        at: string;
      }[];
      const upload = item.upload ? JSON.parse(item.upload).entries || {} : {};
      for (const origin of businessRecordOrigins(task)) {
        let projection;
        try {
          projection = businessRecord(task, origin);
        } catch {
          projection = { result: origin, chain: [origin] };
        }
        const { result, chain } = projection;
        if (
          origin.excluded ||
          result.excluded ||
          !['review', 'submitted', 'failed'].includes(result.status) ||
          (f.source === 'human'
            ? !result.humanReview
            : result.review?.source !== 'codex')
        )
          continue;
        const key = task.id + ':' + origin.id;
        if (scope === 'selected' && !selection.has(key)) continue;
        const query = f.query.toLowerCase();
        if (
          query &&
          ![task.projectName, task.title, origin.prompt, origin.sessionId].some(
            (v) =>
              String(v || '')
                .toLowerCase()
                .includes(query),
          )
        )
          continue;
        if (f.category && origin.category !== f.category) continue;
        const date = result.finishedAt || result.createdAt || '';
        if (
          f.day &&
          new Date(Date.parse(date) + 8 * 3600000)
            .toISOString()
            .slice(0, 10) !== f.day
        )
          continue;
        const members = new Set(chain.map((r) => r.id));
        const history = exports.filter((r) => members.has(r.turnId));
        const count = new Set(history.map((r) => r.batchId)).size;
        if (
          (f.exports === 'never' && count !== 0) ||
          (f.exports === 'exported' && count === 0) ||
          (f.exports === 'exact' && count !== f.count)
        )
          continue;
        const status = upload[key] || {
          status: 'not_uploaded',
          remoteId: null,
          remoteStatus: '',
          reason: '',
          updatedAt: null,
        };
        if (
          f.soloStatus &&
          f.soloStatus !== 'all' &&
          status.status !== f.soloStatus
        )
          continue;
        rows.push({
          row: {
            ...recordRow(
              task,
              origin,
              f.source,
              count,
              history
                .map((r) => r.at)
                .sort()
                .at(-1) || null,
            ),
            soloUpload: status,
          },
          date,
          ordinal: task.turns.findIndex((r) => r.id === origin.id),
        });
      }
    }
    cursor = batch.results.at(-1)!.id;
  }
  rows.sort(
    (a, b) =>
      b.date.localeCompare(a.date) ||
      a.row.taskId.localeCompare(b.row.taskId) ||
      a.ordinal - b.ordinal,
  );
  const total = rows.length;
  const totalPages = Math.max(1, Math.ceil(total / f.pageSize));
  const page = Math.min(f.page, totalPages);
  if (scope === 'filtered' && total > 1000)
    throw Error('筛选结果超过 1000 条，请缩小筛选范围或按页导出');
  return {
    rows: (scope === 'page'
      ? rows.slice((page - 1) * f.pageSize, page * f.pageSize)
      : rows.slice(0, 1000)
    ).map((r) => r.row),
    total,
    page,
    pageSize: f.pageSize,
    totalPages,
  };
}
