import { db } from './store';
import {
  recordRow,
  type RecordFilter,
  type RecordRow,
} from '@/lib/record-fields';
import type { Task, Turn } from '@/lib/pipeline';
export async function selectRecords(
  f: RecordFilter,
  scope: 'page' | 'filtered' = 'page',
) {
  const conditions = [
      "COALESCE(json_extract(r.value,'$.excluded'),0)=0",
      "json_extract(r.value,'$.status') IN ('review','submitted','failed')",
    ],
    args: (string | number)[] = [];
  if (f.source === 'human')
    conditions.push("json_extract(r.value,'$.humanReview') IS NOT NULL");
  else conditions.push("json_extract(r.value,'$.review.source')='codex'");
  if (f.query) {
    conditions.push(
      "(instr(lower(json_extract(t.data,'$.title')),lower(?))>0 OR instr(lower(json_extract(r.value,'$.prompt')),lower(?))>0 OR instr(COALESCE(json_extract(r.value,'$.sessionId'),''),?)>0)",
    );
    args.push(f.query, f.query, f.query);
  }
  if (f.category) {
    conditions.push("json_extract(r.value,'$.category')=?");
    args.push(f.category);
  }
  if (f.day) {
    conditions.push(
      "date(COALESCE(json_extract(r.value,'$.finishedAt'),json_extract(r.value,'$.createdAt')),'+8 hours')=?",
    );
    args.push(f.day);
  }
  if (f.exports === 'never') conditions.push('COALESCE(e.n,0)=0');
  if (f.exports === 'exported') conditions.push('COALESCE(e.n,0)>0');
  if (f.exports === 'exact') {
    conditions.push('COALESCE(e.n,0)=?');
    args.push(f.count);
  }
  const from = `FROM tasks t,json_each(t.data,'$.turns') r LEFT JOIN (SELECT task_id,turn_id,count(*) n,max(created_at) last_at FROM export_items GROUP BY task_id,turn_id) e ON e.task_id=t.id AND e.turn_id=json_extract(r.value,'$.id') WHERE ${conditions.join(' AND ')}`;
  const total =
    (
      await db()
        .prepare('SELECT count(*) n ' + from)
        .bind(...args)
        .first<{ n: number }>()
    )?.n || 0;
  const page = Math.min(f.page, Math.max(1, Math.ceil(total / f.pageSize)));
  if (scope === 'filtered' && total > 1000)
    throw Error('筛选结果超过 1000 条，请缩小筛选范围或按页导出');
  const result = await db()
    .prepare(
      `SELECT CAST(r.key AS INTEGER) ordinal, json_remove(t.data,'$.turns','$.autoGenerated') task, json_remove(r.value,'$.output','$.evidence','$.automation.preparation','$.automation.policy','$.automation.snapshot','$.automation.score','$.automation.next') round,COALESCE(e.n,0) n,e.last_at ${from} ORDER BY COALESCE(json_extract(r.value,'$.finishedAt'),json_extract(r.value,'$.createdAt')) DESC,t.id,r.key LIMIT ? OFFSET ?`,
    )
    .bind(
      ...args,
      scope === 'page' ? f.pageSize : 1000,
      scope === 'page' ? (page - 1) * f.pageSize : 0,
    )
    .all<{
      task: string;
      round: string;
      n: number;
      ordinal: number;
      last_at: string | null;
    }>();
  const rows: RecordRow[] = result.results.map((x) =>
    recordRow(
      JSON.parse(x.task) as Task,
      { roundNumber: Number(x.ordinal) + 1, ...JSON.parse(x.round) } as Turn,
      f.source,
      x.n,
      x.last_at,
    ),
  );
  return {
    rows,
    total,
    page,
    pageSize: f.pageSize,
    totalPages: Math.max(1, Math.ceil(total / f.pageSize)),
  };
}
