import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
export function capacityFor(
  { cores, totalGB, availableGB, load },
  requested = 3,
) {
  const recommended = Math.max(
    1,
    Math.min(4, Math.floor(cores / 3), Math.floor((totalGB - 8) / 6)),
  );
  const hardwareLimit = Math.max(
    1,
    Math.min(4, Math.floor(cores / 2), Math.floor((totalGB - 8) / 6)),
  );
  const maximum = Math.min(hardwareLimit, requested);
  const memorySlots = Math.max(1, Math.floor((availableGB - 2) / 3));
  const loadSlots =
    load >= cores * 1.2
      ? 1
      : load >= cores * 0.9
        ? Math.min(2, maximum)
        : maximum;
  return {
    recommended,
    hardwareLimit,
    effective: Math.max(1, Math.min(maximum, memorySlots, loadSlots)),
    reason:
      memorySlots < maximum
        ? '可回收内存偏低'
        : loadSlots < maximum
          ? '系统负载较高'
          : '资源充足',
  };
}
export function resources(requested = 3) {
  const totalGB = os.totalmem() / 2 ** 30;
  let availableGB = os.freemem() / 2 ** 30;
  if (os.platform() === 'darwin') {
    try {
      const v = execFileSync('vm_stat', [], {
        encoding: 'utf8',
        timeout: 3000,
      });
      const page = Number(v.match(/page size of (\d+)/)?.[1] || 16384);
      availableGB =
        (['free', 'inactive', 'speculative'].reduce(
          (s, k) =>
            s +
            Number(v.match(new RegExp('Pages ' + k + ':\\s+(\\d+)'))?.[1] || 0),
          0,
        ) *
          page) /
        2 ** 30;
    } catch {}
  }
  const metrics = {
    cores: os.cpus().length,
    totalGB: Math.round(totalGB),
    availableGB: Math.round(availableGB * 10) / 10,
    load: Math.round(os.loadavg()[0] * 10) / 10,
  };
  return {
    ...metrics,
    ...capacityFor(metrics, requested),
    cpu: os.cpus()[0]?.model || os.arch(),
  };
}
export function fingerprint(repo, prompt) {
  return createHash('sha256')
    .update(
      repo.replace(/\/+$/, '') +
        '\n' +
        prompt
          .normalize('NFKC')
          .toLowerCase()
          .replace(/[\s\p{P}]+/gu, ''),
    )
    .digest('hex');
}
export function supplyDecision(context, state, now = Date.now()) {
  if (!context.config.enabled) return '自动补充已暂停';
  if (!context.repos.length) return '等待配置仓库，或创建首个手动任务';
  if (context.generatedToday >= context.config.dailyLimit)
    return '已达今日补充上限';
  if (context.queued) return '队列中已有待执行任务';
  if (now < (state.nextAt || 0))
    return state.lastError
      ? '补充失败，退避等待：' + state.lastError
      : '补充冷却中';
  // Stop runaway generation when the execution service or repository keeps failing.
  const recent = context.history.filter((t) => t.autoGenerated).slice(0, 3);
  if (recent.length === 3 && recent.every((t) => t.failed))
    return '最近 3 个自动任务均失败，请处理失败任务后继续';
  return null;
}
